<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (c) 2023-2026 VSK Software GmbH, Bochum, Germany.

This file contains modifications to the original OpenBimRL schema.
The modified schema is distributed under the Creative Commons
Attribution 4.0 International License.

You should have received a copy of the license along with this
work. If not, see <http://creativecommons.org/licenses/by/4.0/>.


An Extension to OpenBIMRL to support multiple BIMRules under the same root.
-->
<schema 
	targetNamespace="http://inf.bi.rub.de/OpenBimRL" 
	elementFormDefault="qualified" 
	xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://inf.bi.rub.de/OpenBimRL">

	<include schemaLocation="OpenBimRL.xsd"/>

    <element name="OpenBIMRL" type="tns:OpenBIMRLType"></element>
    
    <complexType name="OpenBIMRLType">
    	<sequence>
    		<element 
    			name="BIMRule" 
    			type="tns:BIMRuleType"
    			minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="version" type="string" use="required"></attribute>
    </complexType>
    
</schema>
